import { Inter } from 'next/font/google'
import './globals.css'
import styles from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Image from 'next/image'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Image
        src="/casino.jpg"
        width={500}
        height={500}
        className={styles.image}
        alt="Picture of the author"
        />
        {children}
        <footer className={styles.footer}>
        Supermarkets
    </footer>
      </body>
    </html>
  )
}
